name: Simple Pipeline

on:
  push:
    branches:
      - test

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: SCM
        run: echo "this is first stage"

      - name: Build
        run: echo "this is second stage"

      - name: Test
        run: echo "this is third stage"
        
      - name: Quality Check
        run: echo "this is fourth stage"
        
      - name: Artifacts
        run: echo "this is fifth stage"
        
      - name: Infra Provision 
        run: echo "this is sixth stage"
        
      - name: Deployment
        # run: echo "this is seventh stage"
        run: dig google.com
